version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns: ["*"]
        
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0/5 * * * *"
    groups:
      docker:
        patterns: ["*"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
