version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns: ["*"]
        
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # filters:
    #   tags:
    #     - dependency-name: "docker.io/n8nio/n8n"
    #       patterns:
    #         - "^stable$"
